### ISSUE TITLE
Permission denied when deleting files in output folder via ssh

### ISSUE THREAD

**Issue by sonostrano** [ccrisan/motionPie#102]
Hi! Thanks again for this wonderful software.
When I connect to the raspberry and try to use rm -rf * to delete all the folders/file in the folder output, I receive the error "permission denied" or "failure".
Any suggestions?
Thanks

**Comment by ccrisan** [comment]
Can I see the exact commands you enter? What credentials do you use to login via SSH?

**Comment by sonostrano** [comment]
I logged as admin (I tried also logginf as root) and in /data/output I entered  rm -rf *

**Comment by ccrisan** [comment]
What version of motionPie do you run?

**Comment by sonostrano** [comment]
20150112

**Comment by ccrisan** [comment]
This is odd. What does ls -al /data/output say?

**Comment by sonostrano** [comment]
Unable to open -al: no such file or directory
...very strange

I'm using psftp.

by the way... I manually deleted all the files I wanted to delete now

**Comment by ccrisan** [comment]
I thought you were using normal SSH (or putty). psftp doesn't allow normal Linux commands.

**Comment by sonostrano** [comment]
uuu I didn't know, sorry. thank you!
