### ISSUE TITLE
SSH Security issue

### ISSUE THREAD

**Issue by melashkov** [ccrisan/motionPie#105]
I can't seem to find iptables, my motionpie is on public ip and some one constantly trying to ssh, can you please add failed2ban packege or maybe add this script  http://www.pbxer.com/simple-shell-script-to-block-failed-ssh-attempts/

**Comment by ccrisan** [comment]
Adding such scripts to motionPie is simply too specific. I will however add iptables support in the next releases, so enthusiasts can add their own firewall scripts, according to their needs.

**Comment by melashkov** [comment]
thanks :)
