### ISSUE TITLE
Block access from local network's file explorer?

### ISSUE THREAD

**Issue by jpl90** [ccrisan/motionPie#106]
Hi! After using MotionPie 20150112 on my Raspberry Pi B+ with PiCam for about 2 weeks I'm really satisfied! Thank you very much.

I'd like to ask something: is it possible to block access from the local network's file explorer? Or at least ask for user and pass? I'm about to install this and it would be better if people in the local network found it a little harder to view these files...

When I first installed this, in the wiki there was a hint about how to tweak it in an advanced way with some files in the SD card. Now it's not there anymore (I see it was edited) and Ubuntu doesn't recognise the SD card when inserted in my pc. I wanted to access them just in case they had this feature available somewhere (and if it was possible to turn the camera LED off, too). If there are any ideas about this issue, I would be glad to hear them as well.

Thank you very much once again!

**Comment by ccrisan** [comment]
Hi @jpl90,

The documentation has been moved and restructured into a few [wiki pages](https://github.com/ccrisan/motionPie/wiki). You're probably looking for [writeimage.sh info](https://github.com/ccrisan/motionPie/wiki/Installation#write-the-os-image) and [tweaks](https://github.com/ccrisan/motionPie/wiki/Tweaks).

All the writeimage.sh options will soon be available from the UI so everyone can tweak them at any time, without requiring Linux or OSX. I just need some time to properly implement and test them.

Configuring Samba is one of the option that comes now with writeimage.sh and that will be available from the UI soon. You will then be able to configure access to your motionPie network shares.
