### ISSUE TITLE
Email not sending photos

### ISSUE THREAD

**Issue by unmanagedtn** [ccrisan/motionPie#107]
If i setup an smtp server with the latest release it does not send snapshots with the txt motion detected messages... 

Is there something I am missing? setting?

I am using https://mandrillapp.com to send emails ... I use it for a photobooth and its free for 12k per month emails...

**Comment by ccrisan** [comment]
Have you enabled still images? If, at the moment of composing the email, no pictures are found close to the event's moment, no pictures will be attached.

**Comment by unmanagedtn** [comment]
yes I did enable still images ... its set to take a shot every 900
seconds... but that should not have anything to do with it right?

http://71.228.245.100/

**Comment by unmanagedtn** [comment]
I guess you cant do interval and motion capture frames and the same time I
see...

**Comment by ccrisan** [comment]
Nope, you can't.
