### ISSUE TITLE
Motionpie & Raspberry Pi A+

### ISSUE THREAD

**Issue by huuhaa** [ccrisan/motionPie#112]
If I understood correctly, motionPie is supposed to setup by plugin the ethernet cable, entering device IP to the browser of computer and then setting wlan through GUI.

Am I right here? If so, what to do with Raspberry Pi A+ which has no ethernet connection.. What would you recommend? Insert memorycard to linux machine and edit some conf files?

Or just using old model b and inserting memory card to it with that same wlan module. Then entering settings and after all is done, switching card & wlan module back to A+ ?

**Comment by ccrisan** [comment]
All of the above. Whichever you find the easiest.
