### ISSUE TITLE
RPI Dashcam project (may slightly off topic)

### ISSUE THREAD

**Issue by piecam** [ccrisan/motionPie#115]
HI ccrisan,

Just want to get some thoughts from. Would it be possible to turn this motionpie as a Dash cam solution as well?

I have googled on net and there are many solutions around it, with gpio button etc. Do you have any thoughts on this and recommendation?

Best regards and thanks.

**Comment by ccrisan** [comment]
Don't. The framerate is too low for this purpose and the drawn current is, well, let's say considerable. I personally would buy one of the solutions on the market - they seem quite cheap to me.
