### ISSUE TITLE
smb.conf

### ISSUE THREAD

**Issue by snagglewest** [ccrisan/motionPie#119]
All my MotionPie cams disappeared from my network browse which I think is related to the "workgroup = WORKGROUP" entry in the smb.conf which I'm assuming needs to match the name of my homegroup.  I'm able to open smb.conf in nano but it says it's "read only" when I try and save it.  I'm logged in as root and several hours of google has not found an answer... could someone explain what I need to do to edit it (if that's the fix)?

**Comment by ccrisan** [comment]
The workgroup setting shouldn't make your devices disappear. The workgroup should be MOTIONPIE and not WORKGROUP. If you really want to edit it, read the [tweaks](https://github.com/ccrisan/motionPie/wiki/Tweaks) wiki page.

Mind you that the changes you make to smb.conf will be overwritten by the next update.
