### ISSUE TITLE
Working schedule from today to tomorrow

### ISSUE THREAD

**Issue by paolobattistella** [ccrisan/motionPie#123]
Hi,

how it is possible to schedule the working from 11pm of today to 8em of tomorrow?

Thank you
Paolo

**Comment by ccrisan** [comment]
Nope, that is not possible with the existing options.

**Comment by paolobattistella** [comment]
Is it not possible to add the option "23:59" to the next release?

**Comment by ccrisan** [comment]
You can manually type in "23:59" in the input box, after pressing Esc, if that is what you need.
