### ISSUE TITLE
web server app used

### ISSUE THREAD

**Issue by piecam** [ccrisan/motionPie#124]
HI ccrisan,

This is not an "issue". I just want understand a bit better of your distro. I understand to provide web gui support, some use Apache, some use Nginx. It seems that you are not using either.

Can you drop me a quick note or link what apps/tools you use to create that nice web gui experience?
Many thanks

**Comment by ccrisan** [comment]
motionPie is based on [motionEye](https://bitbucket.org/ccrisan/motioneye/), which is a web application developed using the [tornado](http://www.tornadoweb.org/) web framework. There's no nginx or apache involved (yet).

**Comment by piecam** [comment]
thank you very much!
