### ISSUE TITLE
ssh connection refused

### ISSUE THREAD

**Issue by kratostav** [ccrisan/motionPie#129]
Every time when i try to connect via ssh i get this error:
![image](https://cloud.githubusercontent.com/assets/5694929/6512888/58dbf096-c377-11e4-9240-3400e3747cba.png)
network is over WLAN (EDIMAX EW-7811UN Wireless USB Adapter stick)
webUI works fine
IP is static:
![image](https://cloud.githubusercontent.com/assets/5694929/6512934/9bae2ee8-c377-11e4-980a-a36999d093e6.png)
Model RaspberryPi B+
What should i do?

**Comment by ccrisan** [comment]
How about the services section? Can I see a screenshot of that?

**Comment by kratostav** [comment]
![image](https://cloud.githubusercontent.com/assets/5694929/6530606/95903626-c432-11e4-9132-d41d9782153a.png)

**Comment by ccrisan** [comment]
How did you write the image to the sdcard? Can you send me th

**Comment by kratostav** [comment]
with win32diskimager
how will i get this without ssh?

**Comment by ccrisan** [comment]
Insert your sdcard into your pc and, while running Linux, acces the third partition.

You'll find the log directory in the root of that partition. Just compress it and send it to me over by email.

You cannot do that using windows.

**Comment by airtonGit** [comment]
Hi here too, can't connect, stuck in version 20150317...

**Comment by ccrisan** [comment]
Write the image again from scratch and do not disconnect it at first boot within the first 5 minutes.

**Comment by airtonGit** [comment]
Hi, I cant make ssh connection to work, but ok I just take the sd card 
and updated manually, now everything is just fine, Camera Fast Mode is 
so cool! I just cloned the repo and I hope be smart enough to contribute 
some way. thanks!

Em 01/10/2015 03:25, Calin Crisan escreveu:

**Comment by bluevalien** [comment]
I just made my fist blog account to acknowledge this solution.
"Write the image again from scratch and do not disconnect it at first boot within the first 5 minutes."
I did this and now ssh is working without an issue. I have no idea why it was not working before but I think this needs to be an important note for anyone who uses this image.  
Note: You have to use the Administrator username (root did not work for me)
unrelated: This works great! I had been trying to develop my own and gave up now that I've found this. Kudos!  Let me know if there is any way to contribute to the cause. (note: I'm Canadian so my money is practically worthless)
