### ISSUE TITLE
movie lenght motion parameter

### ISSUE THREAD

**Issue by karma007** [ccrisan/motionpie#130]
Hello,

could it be possible to add this motion parameter in the GUI ?

max_mpeg_time	Values: 0 (infinite) - 2147483647 Default: 3600	
The maximum length of an mpeg movie in seconds. Set this to zero for unlimited length.

many thanks !

**Comment by ccrisan** [comment]
Yes. I will consider adding this option to the UI.

**Comment by ccrisan** [comment]
Implemented with the latest motionEye commit. It will be included in the upcoming version of motionPie.
