### ISSUE TITLE
movies are accelerated depending on resolution

### ISSUE THREAD

**Issue by karma007** [ccrisan/motionPie#131]
Hello, i have a picam, with resolution 640x480 -> movies are ok (30' recording = 30' movie file)
with a better resolution (ex: 1024x768) -> movies are accelerated (30' recording = 20' movie file).

does anyone has this problem ?

thanks

**Comment by ccrisan** [comment]
The processing resources are probably not enough when working with a higher resolution and that will cause frame skips. There's nothing I can do - it's more like an upstream motion matter.

If you really need 1024x768, I suggest decreasing the frame rate or buying a RPI2.
