### ISSUE TITLE
MT7601 WiFi Chipset Support

### ISSUE THREAD

**Issue by foxboi84** [ccrisan/motionPie#132]
Hi, Can you advise if it is possible for you to add support for this common wifi chipset. It does not work out of the box and I am unsure if you can just use the 'debian' drivers on buildroot, which MP is based on.

**Comment by ccrisan** [comment]
motionPie uses the kernel (and drivers) that come with raspbian. Moreover, the latest git revision is used whenever a new version is released. There's nothing else I can do about it - I don't have the experience and the time to integrate out-of-tree drivers into kernel.
