### ISSUE TITLE
Is There any way to use Java VM with your motionPie?

### ISSUE THREAD

**Issue by idealist33** [ccrisan/motionPie#133]
Hi I sent my question to you via Gmail but you've not answered...so i write something here..

i want to send messages to my android phone when motion is detected. 
To send messages I want Java Vertual Machine in motionPie
However motionPie does not have java vm...

i tried to build my own iso image but it is very hard for me to do that

i downloaded build source from the URL https://github.com/ccrisan/motionPie/wiki/Building-From-Source
and then After commanding 'build.sh [raspberrypi]' shows 'bad substitution'.

I tried to command 'make' but i have only rootfs.tar file  in output/image folder 
I have only a little knowledge about rootfs..it is super difficult for me.

Do you have any plan to add Java VM to motionPie image for the next update ???

**Comment by ccrisan** [comment]
I really hope you didn't actually type the square brackets around "raspberrypi". The command should read: `./build.sh raspberrypi`.

**Comment by idealist33** [comment]
sorry... it doesn't work at all..here is my ssh command window...

ub@ub-VirtualBox:~/motionFin/motionPie$ sh build.sh raspberrypi
build.sh: 11: build.sh: Bad substitution

=====================================================
is there any way to use java without rebuild your source???

**Comment by ccrisan** [comment]
use `bash` instead of `sh`, or simply type `./build.sh ...`

**Comment by ccrisan** [comment]
I'm sorry, for now please just use `bash` in front of it. If you have `dash` or any other shell set as default on your system, the `./build.sh` won't work. I'll make sure to fix this.

**Comment by idealist33** [comment]
Oh bash works!
if i want to use java, should i do 'make menuconfig' and add jamvm and 'bash ./build.sh raspberrypi' ??

**Comment by ccrisan** [comment]
Yes, that should normally do it, although I did not test it.

**Comment by idealist33** [comment]
Thanks a lot!!! I'll try~ :)
