### ISSUE TITLE
error with open wifi network, no passkey

### ISSUE THREAD

**Issue by rleyden559** [ccrisan/motionPie#134]
I have a Pi A so I followed the procedure to add wpa_supplicant.conf and static_ip.conf to /data/etc under Ubuntu.
The Pi successfully does the first boot and I can configure further in the web interface.
However, under, network there is a red exclamation point in "wireless network key".  My entry for the AP has "key_mgmt=NONE"  in wpa_supplicant.conf.  Blank is not accepted in the web interface.

The web interface will not save any of the changes as long as the red exclamation point is there.
I tried entering None (no quotes) and the Pi rebooted but I couldn't find it on the network.  I ended up re-flashing the SD card and now back to the same point.

Rich

**Comment by ccrisan** [comment]
There's no way to have this working, for now. I will add support for psk-less networks in the next version.

**Comment by rleyden559** [comment]
Thanks.  I found that if I don't expand the network tab I can at least make
and save changes to other fields other fields.  However, the static IP can
only be set or changed by ssh or writing to the SD card.

I'm OK for now.

**Comment by ccrisan** [comment]
The next release will no longer require a wifi network password (key)

**Comment by rleyden559** [comment]
Great!

I really appreciate your approach to MotionPie.  Compared to similar RasPI
projects it is much closer to an embedded device that "just works" .  I've
used Icamview webcam server for the last 5 years.  It's a closed proprietary
system but clearly is based on a relatively low powered linux system.  While
it lacks many features one may wish, each release is indefinitely stable "as
is".  One aspect of the Raspberry Pi I've grown tired off is that
applications tend to die completely if even a minor update is attempted.  

 

Rich
