### ISSUE TITLE
Auto brightness unusable

### ISSUE THREAD

**Issue by jan-r** [ccrisan/motionPie#136]
Hello,

first of all, thanks for this great project, it's never been so easy to get the RasPi up and running as a network cam!

I'm running motionPie on a model A+ with the PiNoIR camera at 1280x720. Everything works fine, but I'm having trouble with changing light conditions outside. After sunrise, the monitored area is very bright and the cam image is near-white. Over the day, it's getting better, although reducing the brightness to 40% improves image quality. In the evening, increasing the brightness can really extend the time the camera delivers a usable image. In short, having automatic brightness would be great. I've enabled the corresponding setting in the UI, but it is not usable for me. Brightness continously modulates from totally dark to bright white within about 10 seconds, then fades back to totally dark.

I've browsed the "Recommended settings" issue, but I was unable to improve this. Is auto-brightness generally usable or just some kind of experimental feature?

Edit: I'm running motionPie 20150228.

**Comment by ccrisan** [comment]
Auto-brightness is a feature known to cause problems and not to work as expected. Unfortunately there's nothing much I can do about it. [Here](http://www.lavrsen.dk/foswiki/bin/view/Motion/ConfigOptionAutoBrightness) is the corresponding motion's option reference. I suggest buying a camera that features autobrightness itself and leave this option off.
