### ISSUE TITLE
minibian+raspMJPEG+Motion+motioneye

### ISSUE THREAD

**Issue by piecam** [ccrisan/motionPie#139]
Dear ccrisan,

I know that we have had conversation about this topic before. However, I am still trying to find out what have to happen that can make you spend some time and effort in considering this.

I know that you have all the knowledges and skills. What I think, is that, you only need to install that RPI Web Interface on a spare pi+pi cam, you will have a first hand experience how Motion is interacting with raspMJPEG program. Then, it might help change your mind of thinking that it might be a good idea, to use your existing motionEYE+minidebian to control Motion, then, use motion to control RPI CAM via raspMJPEG and use motion 's V4L to control USB web cam.

The video/image from raspMJPEG is really very very high resolution and frame rate.(2596 for image and 1080p 25fps for video).

Then you can have one distro with, minibian, motion,motionEye,raspMJPEG; and another distro MotionPie with motion, motionEye, raspMJPEG. Both can incorporate Roberts' scheduling, etc features.

https://github.com/roberttidey/RPi_Cam_Web_Interface (current developer with enhanced web interface and scheduling)

http://www.raspberrypi.org/forums/viewtopic.php?t=63276 (orginal developer with raspMJPEG and web interface)

I know that you are busy with other things and you have your priorities and vision of your distro. However, I was just wondering whether you can take a look first hand and you may reconsider this.

It would always be a wonder to opensource world if these ideas can be brainstormed and worked out.

Once again, many thanks. Please forgive me if you feel that I am a bit irritant.

thanks

**Comment by ccrisan** [comment]
I really don't have the time to look into all this. Sorry.
