### ISSUE TITLE
streaming url unprotected?

### ISSUE THREAD

**Issue by directhub** [ccrisan/motionPie#140]
In version 20150215 with admin and user with their own passwords i can open the streaming url in VLC on my iphone and desktop without any authentication by public ip. So it looks like the live streaming is accessible to anyone knows ip + port, while in the FAQs: "How can I enable authentication for the MJPEG stream?

Simply setting a password for the surveillance user will determine the MJPEG stream to use the surveillance credentials." Am i missing something or the stream is truly "public" despite the FAQ? By the way thanks for this exceptional product Calin.

**Comment by ccrisan** [comment]
The streaming auth is only available in the latest version, which is still a prerelease. Just wait for the next stable release.
