### ISSUE TITLE
Connecting to Stream via app

### ISSUE THREAD

**Issue by JeffGallino** [ccrisan/motionPie#145]
Anyone have any idea how to connect the stream to an android ip camera app? they ask for the url and username/password, but doesn't seem to work. I use the streaming url, i have enabled port forwarding, etc...  the embed url works from my browser on my phone, but not the streaming url.

any suggestion?

**Comment by ccrisan** [comment]
Normally the streaming url should work just fine, as long as your mobile phone can reach your motionPie on port 8081. What version do you use? Newer versions require HTTP digest authentication when a surveillance password is set.
