### ISSUE TITLE
red boxing

### ISSUE THREAD

**Issue by piecam** [ccrisan/motionPie#153]
HI ccrisan,

This is not really an issue, but a question. Why is it red boxing sometimes and not sometimes?
What's the purpose of this and how is it triggered?

thanks
![screenshot from 2015-03-20 17 17 36](https://cloud.githubusercontent.com/assets/10531131/6761033/294ccc42-cf25-11e4-868e-9dc8cc342795.png)
![screenshot from 2015-03-20 17 17 48](https://cloud.githubusercontent.com/assets/10531131/6761034/29591236-cf25-11e4-8d67-ab012e095ddd.png)

**Comment by dkelley810** [comment]
That usually indicates movement was detected.

**Comment by dkelley810** [comment]
I have a question for you? Do you actually have four cameras? and are they plugged into one Pi? Or multiple Pi's?

**Comment by piecam** [comment]
HI dkelley810,
Two pis with pi Cam and usb cam on each pie.

thanks

**Comment by dkelley810** [comment]
Did my explanation of the red box help?
