### ISSUE TITLE
movie frame rate

### ISSUE THREAD

**Issue by piecam** [ccrisan/motionPie#156]
hi ccrisan,

Just a question of frame rate in movie. I noticed the frame rate is 2 in vlc.

Is there a place we can adjust this frame rate to higher value say 15,25, etc for pic cam and usb cam?
or there's a limitation of how high we can go?

Best regards,

**Comment by ccrisan** [comment]
The setting is just an upper limit. You're still bound by the processing power of the platform.

**Comment by piecam** [comment]
hi ccrisan,

sorry, there's a confusion for my part. If it can be changed, where can I change it?
thanks

**Comment by ccrisan** [comment]
You obviously need to change the board (cpu).
