### ISSUE TITLE
Firewall

### ISSUE THREAD

**Issue by thegnnu** [ccrisan/motionPie#157]
Hi Calin Not a issue just a question due to my stupid Virgin Media SuperHub stopping me getting into the motionPie camera's from the web even had port forwarding active the only way was to turn on DMZ so as all ports are now open to the raspberry pi. Would I be able to install a firewall onto the Pi via SSH without causing problem to your software.
TerryR

**Comment by ccrisan** [comment]
Just use the `iptables` command available in motionPie. The following lines would do the trick:

    iptables -P INPUT DROP
    iptables -A INPUT -p tcp --dport 80 -j ACCEPT
    iptables -A INPUT -p tcp --dport 8081 -j ACCEPT
    iptables -A INPUT -p tcp --dport 22 -j ACCEPT

There's no support for custom commands to be run at startup (i.e. no `rc.local`), but I will consider adding one.

**Comment by thegnnu** [comment]
On 25/03/2015 08:10, Calin Crisan wrote:
>
> Just use the |iptables| command available in motionPie. The following 
> lines would do the trick:
>
> |iptables -P INPUT DROP
> iptables -A INPUT -p tcp --dport 80 -j ACCEPT
> iptables -A INPUT -p tcp --dport 8081 -j ACCEPT
> iptables -A INPUT -p tcp --dport 22 -j ACCEPT
> |
>
> There's no support for custom commands to be run at startup (i.e. no 
> |rc.local|), but I will consider adding one.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ccrisan/motionPie/issues/157#issuecomment-85909614>.
>
Thanks for your reply I will try that on my return home

TerryR

**Comment by ccrisan** [comment]
The latest version has support for user-defined [startup commands](https://github.com/ccrisan/motionPie/wiki/Tweaks#adding-custom-startup-commands). You could place your firewall rules in there.
