### ISSUE TITLE
Add CPU load average to control panel

### ISSUE THREAD

**Issue by jepolch** [ccrisan/motionPie#158]
I thanked you personally in email, but I'll request a feature here. Can you please add the CPU load averages, ala 'top', somewhere on the control panel screen? Then we'll know if we're pushing the Pi too hard. Also, the CPU temperature would be nice to know. 

There's a nice project on github called RPI-Monitor (https://github.com/XavierBerger/RPi-Monitor) which can give the stats, but I don't believe we can install that on the Pi running motionPie, is that correct?

Thanks again!

**Comment by ccrisan** [comment]
Such monitoring tools are beyond the scope of motionPie, which is going towards a board-agnostic surveillance system.
