### ISSUE TITLE
Motion Notifications Web Hook URL

### ISSUE THREAD

**Issue by Colbey** [ccrisan/motionPie#163]
Are there plans, or is there a configuration option currently available, that allows the "Web Hook Notifications" to attach the same images that would get sent in the email notification, in the POST data?

**Comment by ccrisan** [comment]
Yes, there are some plans in this direction but I am quite busy these days and I simply don't find the time to implement this feature.

**Comment by Colbey** [comment]
noted. thanks for keeping us informed, and thanks for an amazing project!
