### ISSUE TITLE
Extra motion options is striping ampersand from url 

### ISSUE THREAD

**Issue by galactic-void** [ccrisan/motionPie#165]
I'm trying to setup an ip camera with the user/password embedded in the url however each time the config for the camera is saved the ampersand in the url is striped.

Example (Extra motion settings):
`netcam_url http://<ipaddress>/videostream.cgi?user=name&pwd=pass`

Result:
`netcam_url http://<ipaddress>/videostream.cgi?user=namepwd=pass`

Expected:
`netcam_url http://<ipaddress>/videostream.cgi?user=name&pwd=pass`

**Comment by ccrisan** [comment]
It's fixed in upstream motionEye with the latest commits. The next motionPie version will hopefully work just fine for you.

**Comment by ccrisan** [comment]
The [latest version](https://github.com/ccrisan/motionPie/releases/tag/20150331) should fix your problem.
