### ISSUE TITLE
Low latency

### ISSUE THREAD

**Issue by abocin** [ccrisan/motionPie#167]
I have though one additional question.

The camera seems to have some latency. Is there any chance to reduce the latency below 1s?

Thanks.

**Comment by ccrisan** [comment]
Not really.

**Comment by abocin** [comment]
https://forums.openpilot.org/topic/26613-raspberry-pi-camera-latency-testing/

**Comment by ccrisan** [comment]
There's a limitation coming from the motion daemon. Everything has to go through the CPU and cannot be accelerated. So no advantage taken from using the PI camera.
