### ISSUE TITLE
Choppy Video

### ISSUE THREAD

**Issue by Hoenerk** [ccrisan/motionPie#171]
I love this program, thank you so much for making available. I set up a motion pie yesterday and have just started playing with it. I noticed that the video playback was extremely choppy, looked more like a photo slideshow. I was wondering, could tell me which parameters I could try to adjust to get the video smoother and possibly reduce the lag on the live feed?

**Comment by ccrisan** [comment]
The choppiness is due to the rather limited performance of the board. Either decrease the resolution or the video device framerate (or both).
