### ISSUE TITLE
Low framerate video

### ISSUE THREAD

**Issue by bdalton12** [ccrisan/motionPie#175]
Video is captured at 1 or 2 frames per second.  The python script mentioned [here](http://www.raspberrypi.org/forums/viewtopic.php?p=662008#p662008) allowed me to get 15 fps video from the Raspberry Pi B+.  It'd be cool to merge this somehow into motionPie.  Keep up the great work!

**Comment by ccrisan** [comment]
It's impossible to merge that script into motion's functionality. The closest to that integration is [motion-mmal](https://github.com/dozencrows/motion/tree/mmal-test) which is included as an alternative with motionPie, but which doesn't bring any sensible fps improvements.
