### ISSUE TITLE
Cameras Swap Numbers

### ISSUE THREAD

**Issue by jepolch** [ccrisan/motionPie#176]
It seems whenever I reboot or power cycle the Pi the camera numbers change. Camera1 becomes Camera3, etc. This is not a serious issue, however, the settings remain with the number and don't follow the camera. Is this a known issue? Is there any way to freeze the camera association? Thanks again, Calin.

**Comment by ccrisan** [comment]
It's a known issue and it is kind of a serious one. It has been reported here: https://github.com/ccrisan/motionPie/issues/120. I'll think of a solution.

**Comment by ccrisan** [comment]
Fixed! See https://github.com/ccrisan/motionPie/issues/120
