### ISSUE TITLE
No connection when SSID has space in it

### ISSUE THREAD

**Issue by esyscoder** [ccrisan/motionPie#18]
I had to change my network SSID because old one had space in it and this caused wifi to not connect to AP.  Something to look at when you have WiFi issues.

**Comment by ryderstorm** [comment]
This caused me an issue too, but you can use network names with spaces. You just need to surround the network name with single quotes. The following install command allowed my Pi to connect to my network **The Batcave** with no issues:
`./writeimage.sh -d /dev/sdd -i ~/Desktop/motionpie-raspberrypi-20150215.img -n 'The Batcave':wifipassword`

I had to add a line to `writeimage.sh` to help troubleshoot the issue. I submitted a [pull request](https://github.com/ccrisan/motionPie/pull/118) so other people could avoid the issue.

**Comment by ccrisan** [comment]
The new (yet-to-be-released) version incorporates UI for all these settings. `writeimage.sh` will soon become obsolete.
