### ISSUE TITLE
unable to open video device

### ISSUE THREAD

**Issue by KyleBeam** [ccrisan/motionPie#181]
Hey I have an issue where when I add a camera, it gives me the dreaded: "unable to open video device" message. I've just installed the latest version of motionpie: motionpie-raspberrypi-20150331, and my raspberry pi is connected over ethernet. The camera that I have is a Dahua POE camera, which is plugged in with an ethernet cable to a POE switch. I can navigate to the IP address of the camera and see live video and access the little web server controls that is has built in to it, although the web interface did make me install an Active X plugin to Firefox in order to see any video. When I added the camera in motionpie, I went to: add camera > Device: network camera, URL: http://192.168.1.108, Username: admin, Password: admin. When the URL field loses focus, a message in red color pops up beside Camera that says: "not a network camera". There's some info in /var/log/motioneye.log but I'm not sure what it means. Thanks for the help, I really appreciate what you've done here with motionpie, it's worked great for me with a USB camera connected in the past. 
![screen shot 2015-04-15 at 9 39 20 pm](https://cloud.githubusercontent.com/assets/6708131/7173139/778204b6-e3b8-11e4-9984-fa7cc42cad50.png)
![screen shot 2015-04-15 at 9 39 09 pm](https://cloud.githubusercontent.com/assets/6708131/7173141/7a88d1ee-e3b8-11e4-8d8b-150eed4c8b6b.png)
![screen shot 2015-04-15 at 9 41 07 pm](https://cloud.githubusercontent.com/assets/6708131/7173142/7c9d1e22-e3b8-11e4-9655-e062ffaebbcf.png)

**Comment by ccrisan** [comment]
If the dialog says "not a network camera", then the URL you provided does not serve JPEGs or MJPEGs. Consult your camera to find out what correct MJPEG url is (if it's supported at all).
