### ISSUE TITLE
Automatic Update ate motionPie

### ISSUE THREAD

**Issue by jepolch** [ccrisan/motionpie#188]
"when your motionPie gets back, the update function should work just fine"

I followed the instructions here: https://github.com/ccrisan/motionpie/releases/tag/20150331 to modify update.py (copied and pasted) and rebooted. After that, I clicked Check and was asked if I wanted to update to 20150331. I clicked "yes" and it broke motionPie. It would not start after that. I couldn't ping the Pi. Not a big problem. I just wrote a new SD card and now it's back again and working fine. Just thought I'd mention it.

**Comment by ccrisan** [comment]
Sorry about that. The update mechanism is far from perfect and has its flaws.
