### ISSUE TITLE
An error occurred. Refreshing is recommended.

### ISSUE THREAD

**Issue by jimmyeao** [ccrisan/motionpie#189]
I get the above error when trying to access the list of stored videos, or when applying any settings change. 
Version 20150331 on a B+

**Comment by jimmyeao** [comment]
Hmm. This seems to have resolved itself after a 3rd reboot. But it bugs me I don't know why it happened. All I changed was the patch to get updates working.

**Comment by ccrisan** [comment]
Most likely the browser's cache kept the old version of the javascript file(s) and they are incompatible with the new version. It probably expired afterwards and the browser asked for the new version, which now seems to work.
