### ISSUE TITLE
Local Disk Fallback When Recording To SMB (NAS) Fails

### ISSUE THREAD

**Issue by Jasimo** [ccrisan/motionpie#196]
Hi, as Iam new to motionpi I have a question regarding SMB recording.
When I set the recording to a NAS via SMB (NFS is not possible, isn´t it?) what happens wenn the NAS failes or the network connection is interrupted. Is there any buffering of the recorded files locally on the PI?
rgs
Jan

**Comment by ccrisan** [comment]
When the NAS fails, your video stream is interrupted and everything is lost. There's no fallback and there's no easy way to implement one.

motionPie does not support NFS.

**Comment by Jasimo** [comment]
would be a nice feature. But it should be possible to record locally and copy all records older then x to the nas to keep the local storage free?
