### ISSUE TITLE
Spaces in passwords make it unable to SSH into motionPie

### ISSUE THREAD

**Issue by BeanBagKing** [ccrisan/motionpie#198]
To recreate, log in and set an admin password via the UI to anything containing spaces, for example, "pass word". Reboot and try to SSH to the box. You should get the following error.

root@box:~# ssh 10.0.0.17
Welcome to mp-xxxxxxx!
root@10.0.0.17's password: 
Permission denied, please try again.
root@10.0.0.17's password: 
Permission denied, please try again.
root@10.0.0.17's password: 
Permission denied (publickey,password,keyboard-interactive).
root@box:~#

Logging in through the web UI still works fine.

I know this isn't a problem on other linux boxes (spaces in passwords). It's probably low hanging fruit for motionPie, but I hope it gets solved one day because I use passphrases for a lot of things.

Thanks.

**Comment by ccrisan** [comment]
I will take a look into this.

**Comment by ccrisan** [comment]
The problem has been fixed. The fix will be included in the next version.
