### ISSUE TITLE
No Picture using Pi Noir with Motionpie

### ISSUE THREAD

**Issue by Chip-DFIR** [ccrisan/motionpie#199]
Hi 

I have setup and installed using the motionpie-raspberrypi2-20150331.img.gz image

I have the webgui up and running and it has detected the camera but the screen shows:

![capture](https://cloud.githubusercontent.com/assets/8768477/7650013/46c1840c-faea-11e4-88ee-1f643d0cc2b5.PNG)

and on the monitor I have plugged into the Pi  I get an error that refreshes every 30 seconds or so with different numbers at the start but ending:

bcm2835-v412: error 0 waiting for frame completion

Each time the error repeats the red led on the noir blinks off then on.

Has anyone else had this issue or know of a fix please?

**Comment by ccrisan** [comment]
Does it work with raspbian?

**Comment by Chip-DFIR** [comment]
I'm not sure I have only tried your raspberry pi2 image as I was following the guide.

Should I install Raspbian then install from source?

**Comment by ccrisan** [comment]
Nope. Just install raspbian and see if other v4l2 applications work with the camera, so we can rule out a hardware fault.

**Comment by Chip-DFIR** [comment]
What other applications should I try? Sorry quite new to the Pi and the camera

**Comment by ccrisan** [comment]
First try to see if [raspistill](https://www.raspberrypi.org/documentation/usage/camera/raspicam/raspistill.md) works.

Then you can `sudo modprobe bcm2835-v4l2` to have the v4l2 driver loaded and you can `sudo apt-get install camorama` to test the v4l2 interface.

**Comment by Chip-DFIR** [comment]
When I try Raspistill I am getting the following error:

mmal: No data received from sensor. Check all connections, including the sunny one on the camera board.

I have reseated the cable with no joy though.

**Comment by ccrisan** [comment]
Then I suspect a hardware problem.
