### ISSUE TITLE
Raspberry Pi camera shortfalls

### ISSUE THREAD

**Issue by morph666** [ccrisan/motionPie#20]
Amazing project, I've got 2 RPI's running wirelessly outside my workshop.

I've got an issue with the actual camera on the Pi. During sunrise and sunset the camera's brightness doesn't seem to adjust properly. Leaving the image either very light or in the case of sunset, very dark. I realise this is hardware issue, but would it be possible to refresh the camera every half hour automatically?
I've found that adjusting the brightness all the way down and the then back to 50% fixes the issue

Thanks for your hard work

Lee

**Comment by sh2515** [comment]
Thanks for fixing the v4l2 issue.
I have tested by issuing a v4l2-ctl command to see if it restarts the auto exposure. The reason for this being the initial start of the camera adjusts correctly but doesn't continually change the exposure as necessary. however if I change something in the settings in motioneye website it restarts something to obtain the correct exposure settings for that instant.  What does the apply button do? what file is being updated to restart the camera?

**Comment by ccrisan** [comment]
The apply button does various things, depending on the settings that have been changed. In a nutshell:
 * if one of the main settings has been modified, it simply applies and persist that setting
 * if one of the *local* camera settings has been changed, it updates the config file(s) and restarts the motion daemon
 * if one of the *remote* camera settings has been changed, it sends the apply "command" to the remote instance
 * if wireless settings have been changed, it updates the wpa_supplicant.conf file and reboots

Motion daemon restarting will reinitialize the camera so I believe this is what you're looking for.

**Comment by lastfreenick** [comment]
Just updated to latest stable and auto brightness seems to do rather well with the pi cam. It kind of freaks out in near darkness but low light performance is much better. Just like others reported here,  the camera did hardly adjust to brightness changes before but now, at leat with auto brightness enabled, it seems to do the job.

**Comment by ccrisan** [comment]
Unfortunately there's nothing I can do to improve the situation. I will now close the issue and should anyone come up with further details or workarounds, I'll be happy to reopen it.

**Comment by sh2515** [comment]
Hopefully my comment will not reopen the issue automatically, however I would like to help with this issue.
Is there any documentation for v4l2? I am unable to find any concise infromation
I am curious about the input channel as the picamera has 4 and 0 is generally for stills.  When i query v4l2 0 is the input channel
```
ioctl: VIDIOC_ENUMINPUT
	Input       : 0
	Name        : Camera 0
	Type        : 0x00000002
	Audioset    : 0x00000000
	Tuner       : 0x00000000
	Standard    : 0x0000000000000000 ()
	Status      : 0x00000000 (ok)
	Capabilities: 0x00000000 (not defined)
```
and when I query ouput i get this
`VIDIOC_G_OUTPUT: failed: Inappropriate ioctl for device`
However I would like to read some documentation before I try any adjustments to aid fault finding and fixes.

**Comment by lastfreenick** [comment]
I've been playing around with the settings in the motion.conf file (/data/etc/thread-1.conf) trying out differents settings.  After setting brightness, contrast and saturation to zero  (which should disable these settings, from what I understand) the pi cam brightness hasn't got stuck for two days now. 

This might actually be a fix for the brightness hang issue of the pi cam. I don't know how or why it works, but it does!

**Comment by DanTheColoradan** [comment]
I definitely feel like the auto brightness detection isn't very good. I doubt I have the skills to fix it, but I think I'll check out the Motion project and see if anything is going on.

**Comment by lastfreenick** [comment]
Brightness is messed up again after 3 days so messing with settings in motion.conf doesn't seem to do help much

**Comment by henrik1g** [comment]
I am not using motionPie. Instead raspbian with official v4l2 driver and motion.
However I stumbled upon this thread because I also had the brightness lockup issue.

The official v4l2 driver has a problem with exposure in stills mode. Stills mode is automatically selected when resolution is higher than 1280x720.
You can change that with parameters for the kernel module:

sudo modprobe bcm2835-v4l2 max_video_width=2592 max_video_height=1944

to keep the cam in video mode.
As for now this resolves the exposure issue for me :-) 
I got this info on the v4l2-driver-thread
http://www.raspberrypi.org/forums/viewtopic.php?f=43&t=62364&start=329#p696673

Hope this helps you too.

**Comment by ccrisan** [comment]
Thanks for the tip @henrik1g! I knew there was a threshold above which the CSI camera would choose stills mode, I just didn't know it was configurable, though. I will run some tests and will make sure to add these parameters to the module.

**Comment by lastfreenick** [comment]
Now that are some great news. MMAL stills mode still does the trick for me but in this mode the framerate is at something like 0.3 frames per second, which is a bit slow.
