### ISSUE TITLE
continous reboot raspberry pi 2

### ISSUE THREAD

**Issue by mdotoum** [ccrisan/motionpie#203]
greetings crisan,

i have a raspberry pi 2 running motionpie 2

i write the image do the settings then i do a shutdown

after i reconnect it to power up the power blinks once with a green light .. then 10 seconds later the led for the csi camera is on then 2 seconds later it reboots for no reason 
![screenshot from 2015-05-25 14 23 52](https://cloud.githubusercontent.com/assets/402573/7796613/b406ae1e-02e9-11e5-8507-e3d4c2d22f9e.png)

this is the log for motioneye

the only way i can fix it is by re writing the image again

any ideas?

**Comment by ccrisan** [comment]
Please send me the boot.log file.
