### ISSUE TITLE
Invalid Credential error

### ISSUE THREAD

**Issue by kiuuby** [ccrisan/motionpie#206]
Hi,im getting a invalid credentials error when im trying to add a webcam. I can login the first time,change the password for admin and user, use ssh , but when i try to add a camera it gives this error. I've tried with my password, admin/root , the pi serial , leave it blank ,i tried everything but nothing. Can you help me?

**Comment by oopeekoo** [comment]
Same here with Microsoft LifeCam HD. Switched to Logitech HD camera, no credentials asked anymore.

**Comment by ccrisan** [comment]
Could you please send me the motioneye.log file and a screenshot of the Add Camera dialog when the name of the camera is visible? It might have to do with some special characters in the camera's name.

**Comment by kiuuby** [comment]
I've got the same camera! right now im away and i cant upload the log or the screen sorry

**Comment by oopeekoo** [comment]
Troublesome Microsoft camera showed up with full model name, working Logitech is just "V4L2 Camera".

**Comment by ccrisan** [comment]
It might be the special (R) character in the camera name. I'll investigate the problem and come back with an answer.

**Comment by wbrownp** [comment]
Hi, 
Just wanted to leave a quick note to say that I am too experiencing the same issue as oopeekoo. Trying to add a Microsoft Lifecam 3000 and credentials are not being accepted. Thanks

**Comment by ccrisan** [comment]
[This](https://bitbucket.org/ccrisan/motioneye/commits/413e5ee41b6e688992cb9a77a10335a7c6eea1a1) motionEye commit fixes issues with Microsoft (R) cameras. The fix will be included in the next release.
