### ISSUE TITLE
cant change Frame Change Threshold

### ISSUE THREAD

**Issue by cdnr1** [ccrisan/motionpie#210]
when i change Frame Change Threshold it won't detect motions any more and stops making picture stils 
i have a raspberry pi 2 and a pi cam

**Comment by ccrisan** [comment]
That doesn't mean you can't change it. Set it to a limit that detects motion correctly.

**Comment by cdnr1** [comment]
when i change it from the defualt setting it stops working even if i set it back at the defualt setting
