### ISSUE TITLE
When file storage runs out?

### ISSUE THREAD

**Issue by github-0** [ccrisan/motionpie#213]
Hi,

What happens when the file storage is full? No more saving motion events? Automatic deletion of older material? Complete meltdown?

I guess I could do my own script to delete older material as needed and schedule it to run with Cron?

**Comment by ccrisan** [comment]
Older media files could be removed automatically based on their creation time. The lifetime of pictures as well as of the movie files can be configured from the settings panel.

When the storage is full, the behaviour is unpredictable. I believe the motion events would have to suffer.
