### ISSUE TITLE
Big FontSize for some resolutions

### ISSUE THREAD

**Issue by LiviuShiva** [ccrisan/motionpie#217]
Hi,

I'm using 2 Microsoft (R) Lifecam 3000. Choosing from the available resolutions, I noticed that 416x240 display a bigger font than 320x240:
![image](https://cloud.githubusercontent.com/assets/3812469/8148286/139b41e0-129f-11e5-80ac-e1e31357bfed.png)

The font is too big, from my point of view, for 176x144 also.

**Comment by ccrisan** [comment]
There are only [two possibilities](http://www.lavrsen.dk/foswiki/bin/view/Motion/ConfigOptionTextDouble) when it comes to the text size. Given this restriction, there will always be resolutions at which text will be too large or too small. Unfortunately there's not much I can do about it.
