### ISSUE TITLE
Samba

### ISSUE THREAD

**Issue by wolverine-forever** [ccrisan/motionpie#219]
Due to the fact that I would like to use the share on a server outside my network I have trouble to get it up.
It was recommended to use SSHFS for that or a VPN.
However both not really possible. VPN not due to the fact that it can't be installed.. but sshfs not due to fuse.

Anyone a solution? I would like to store a copy of files outside my network .

regards, wolverine_forever

**Comment by ccrisan** [comment]
Configure a VPN on a separate computer inside your local network.
