### ISSUE TITLE
not a supported network camera error

### ISSUE THREAD

**Issue by Cyril25** [ccrisan/motionpie#220]
Hi,
I've a Raspberry Pi 2 with motionpie and I've connected an USB camera with no issue, but for the second one, I see the message "camera not supported", 
I bought this camera on aliexpress http://www.aliexpress.com/snapshot/6506544487.html?orderId=65926957675420
Do you think that this camera is compatible with motionpie or not ?
Do you have a list of “low price & good image quality” ip camera compatible with motionpie ?
Thank you for your help

**Comment by ccrisan** [comment]
There's no list of supported IP cameras. Unless the IP camera has support for MJPEG streaming, it won't work with motionPie. I couldn't find this information in the link you sent me. Where do you see the "camera not supported" message? Could you send me a screenshot?

**Comment by Cyril25** [comment]
Sorry for the delay, I was not at home,
Here attached the screenshot,

![cam_message](https://cloud.githubusercontent.com/assets/12915085/8262802/77b2d9b0-16d5-11e5-95b4-ac16a039194f.JPG)
![cam_message2](https://cloud.githubusercontent.com/assets/12915085/8262803/77b81ad8-16d5-11e5-8d63-9a0ac5749325.JPG)

I can see the video directly with the web interface of the camera, but it's not working with motionpie
Do you need something else ?
Thank you for your help

**Comment by ccrisan** [comment]
The message is a bit different than what you said and indicates that the network camera most likely uses HTTP Digest authentication which is not supported by motion. I'm sorry but there's nothing I can do about this.

**Comment by Cyril25** [comment]
OK thank you for tour help.Can you suggest me some network camera with good image quality, not very expensive and working with motion please?ThxCyril

Envoyé de mon Galaxy S5 Orange

-------- Message d'origine --------
De : Calin Crisan <notifications@github.com> 
Date : 2015/06/19  22:57  (GMT+01:00) 
À : ccrisan/motionpie <motionpie@noreply.github.com> 
Cc : Cyril Samson <cyril.samson@free.fr> 
Objet : Re: [motionpie] not a supported network camera error (#220) 

The message is a bit different than what you said and indicates that the network camera most likely uses HTTP Digest authentication which is not supported by motion. I'm sorry but there's nothing I can do about this.
