### ISSUE TITLE
Manual time setting

### ISSUE THREAD

**Issue by mkampstra** [ccrisan/motionpie#223]
Im running motionPie @ raspberry 2B. When i run it at home it can load time from NTP timeservice.
When im using it at work, im not allowed to run the camera through the open network because of privacy issues. Im using it to track some errors in our production.
So when not connected to internet, no time. It's set at 01-01-1970.

Im able to set time manually with SSH. But everytime i do, the pi reboots and date en time are set back to 1970. I now did a perform action on motion, run command, to set the time. But it's very un usefull.

Why is the system going down on setting time and date through ssh.

Is it possible to add an manual time setting?

**Comment by ccrisan** [comment]
Use the HTTP date method (by default, Expert Settings). Manual date is useless as the drift is too big and the error can be as high as a half an hour for a day.
