### ISSUE TITLE
Lifetime max 4 hours with 2 cams

### ISSUE THREAD

**Issue by rv32** [ccrisan/motionpie#231]
Hi,
If use only the CSI PiCam only everything is perfect! When I add a low cost USB camera, it works fine during maximum 4 hours (between 1 & 4 in fact) & then the raspberry crashes.
To try to fix that I've set the GPU memory to 448 (max) without effect, raspi freeze after a few hours.

RV

**Comment by ccrisan** [comment]
The usb camera (driver) may be buggy. Try with another usb camera or try the usb camera for 4+ hours with raspbian. I'm afraid there's not much I can do to help you with this problem.

**Comment by ccrisan** [comment]
It would also help us if you mentioned the model of your camera (in the issue's title, preferably).

**Comment by rv32** [comment]
Thanks for your reply. The problem is I don't know the model of this USB cam ! It's from "shenzen direct" at €2.5 !Absolutely no name on it. I was happy to make it work at the first time but not for a long time!

**Comment by ccrisan** [comment]
Well in that case I'm sorry but I have no solution for your issue.

**Comment by rv32** [comment]
Is there a method to get the camera type even if there's nothing written on it?

**Comment by ccrisan** [comment]
lsusb on a Linux machine (other than motionPie).
