### ISSUE TITLE
Can't remove 'extra motion options'

### ISSUE THREAD

**Issue by SuperSharpShooter** [ccrisan/motionpie#245]
In the extra motion options field, I set 'area_detect 456', but then decided to remove that and replace it with 'mask_file /home/ftp/sdcard/mask.pgm'

After I hit apply with only the mask_file line in the box, it refreshes with both the area_detect, and mask_file lines there. even if I clear the box and hit apply, both lines appear again once the screen refreshes.

**Comment by ccrisan** [comment]
Yes, I can reproduce the bug. Thanks for reporting it.

**Comment by ccrisan** [comment]
Fixed in upstream motionEye 0.25.1.
