### ISSUE TITLE
Crontab

### ISSUE THREAD

**Issue by ubbosabbat** [ccrisan/motionpie#255]
Hi,
i just discover motion pie
it is very great, i have installed it on my 4 Pi
and its working great, i was using a crontab to shutdown my cameras
but i dont find it in the system, is there someting elese to do it ?

thanks again a lot for this 

bye

**Comment by ccrisan** [comment]
See [this](https://github.com/ccrisan/motionpie/wiki/Tweaks#running-commands-at-regular-intervals-cron-support).

**Comment by ubbosabbat** [comment]
Thanks a lot for the cron 
its working great
