### ISSUE TITLE
Syncthing

### ISSUE THREAD

**Issue by chrisveness** [ccrisan/motionpie#258]
Would it be possible to install [Syncthing](https://syncthing.net#main) on MotionPie?

When I try, I get a message `FATAL: mkdir /home/ftp/.config: read-only file system`.

**Comment by ccrisan** [comment]
There are no plans to integrate such third-party addons.

**Comment by chrisveness** [comment]
I wasn't intending it as an add-on, I was more wondering if there's any way around the 'read-only file system'. I guess not.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motionpie/wiki/FAQ#why-do-i-get-read-only-file-system-when-trying-to-edit-a-file

**Comment by chrisveness** [comment]
Thank you! I missed that FAQ, somehow – very useful...
