### ISSUE TITLE
Include option to handle unruly webcam autofocus

### ISSUE THREAD

**Issue by TravisCHoward** [ccrisan/motionpie#263]
There are at least two models of Microsoft LifeCam webcams that refocus for seemingly no reason every 10 to 30 seconds. This triggers motion detection and so I have an abundance of worthless videos of the webcam refocusing. I Have found two methods to disable the autofocus and then set the focus to "infinity," which provides a clear image anywhere from a foot or so all the way to about 150 feet away. It seems the focus on these cameras works best set to 0 anyway.

## Method 1 (not working on motionpie)
uvcdynctrl allows the autofocus to be disabled but isn't included in motionpie. There are specific details here: http://www.bot-thoughts.com/2013/01/lifecam-hd-6000-autofocus-fix-raspberry.html

## Method 2 (*working on motionpie*)
I was able to ssh into motionpie on my RasPi B+ and use v4l2-ctl to fix the focus problem on my LifeCam Cinema.

`v4l2-ctl -l` will list all controls and their values, I noticed that **focus_auto** was set to **1** and **focus_absolute** was set to **24**. The following commands solved the autofocus problem for me.

    v4l2-ctl -c focus_auto=0
    v4l2-ctl -c focus_absolute=0

Please provide a way to either run a script so that we can manually fix this issue or provide access to v4l2 configuration from the web GUI.

**Comment by ccrisan** [comment]
Including uvcdynctrl is something that makes sense. I'll see if I can compile it for ARM. Nevertheless, executing scripts at startup is achievable using /data/etc/userinit.sh. See [Adding Custom Startup Commands](https://github.com/ccrisan/motionpie/wiki/Tweaks#adding-custom-startup-commands).

**Comment by ccrisan** [comment]
libwebcam/uvcdynctrl support has been added
