### ISSUE TITLE
UI for reviewing captured motions

### ISSUE THREAD

**Issue by dattanchu** [ccrisan/motionpie#267]
In order to view the captured motion videos, users have to get to the data via one of the storage protocol (SSH, FTP, ...). This feature requests that we add a new tab to the MotionPie web application that allows the following tasks

* View the list captured motion video ordered by the camera
* Filter on these videos based on camera and date/time
* View the actual video on the web app

I would be happy to help develop this feature improvement. Is there an existing effort in this matter?

Estimated time: 40 hours.

**Comment by ccrisan** [comment]
1) Viewing the list of media files, "ordered" by camera is already possible using the media browser. Filtering them by date/time is implicitly achieved if the file names include this information (which they do by default).

2) Viewing the video online is not currently possible, as the video format used by motion is not compatible with HTML5. Flash-based players are out of question.

3) Uploading media files to remote storage is an issue that needs to be done and is one of my priorities. This is the original issue: https://github.com/ccrisan/motionpie/issues/161.
