### ISSUE TITLE
Cannot open stream properly from XBMC

### ISSUE THREAD

**Issue by Vaevictus** [ccrisan/motionPie#28]
Hi there, 

nice image. had some fun setting up a pi today with this software.

I've tried setting up my XBMC media center to be able to open up the stream produced (http://someip:8081) and XBMC struggles with the stream and keeps trying to buffer it. VLC however plays it back great.

Is there a reason XBMC might be having trouble? would other protocols be better such as RTSP?

also during my googling of the issue I came across some files in this repo regarding xbmc pvr addons. That would be a great too....

**Comment by stoffej** [comment]
works for me...

i created a file with extension *.strm
the file contains 
"http://IP_OF_YOUR_MOTIONPIE:8081" 
remove the quotes and replace the IP
works on Kodi  5.0
