### ISSUE TITLE
FTP server directory empty

### ISSUE THREAD

**Issue by rv32** [ccrisan/motionpie#281]
Hi,
 I've enabled the FTP server feature.
I use a USB stick formated FAT32.
Everything seems OK excepted the folder MyPi/storage/sda1 is empty!
Tested with windows explorer, FireFTP & FileZilla : same result.
Using samba share at the same time, the same folder contains recordings & snapshots.
The credentials used for FTP access are the same as for motionpie admin  login.
Any explanations ? Thanks in advance.

**Comment by ccrisan** [comment]
This is (was) a known bug, fixed with some recent commits. Please hang on another few weeks until the new version is out.

**Comment by rv32** [comment]
Ok. thanks .
