### ISSUE TITLE
Rename Admin

### ISSUE THREAD

**Issue by bjs-pdx** [ccrisan/motionpie#286]
Is there a way to rename the admin account?  I always like to remove any default accounts or rename them.  I've set a password but leaving the account as admin seems wrong.

**Comment by ccrisan** [comment]
You cannot and you should not change that user; it's an alias for "root" and it is used for many services (e.g. motionEye, SSH, FTP, samba). Leaving the account as admin should not seem wrong at all. Leaving an empty password should!
