### ISSUE TITLE
Can't add IP cameras

### ISSUE THREAD

**Issue by brunomariani** [ccrisan/motionpie#293]
![ip camera](https://cloud.githubusercontent.com/assets/10342209/9720777/17a57812-5568-11e5-8e58-0487eedc717e.png)

Hi!

I've tried to add 4 IP cameras from different brands (Tenvis, EasyN, Suneyes, Wanscam), but none of them was accepted. It says: "not a supported network camera".

What kind or models of IP cameras are supported?

Regards,

Bruno.

**Comment by ccrisan** [comment]
All IP cameras that speak MJPEG or JPEG are supported. Soon there will be support for RTSP cameras. Your problem is most likely the fact that the URL you entered is not the (M)JPG URL of your camera but rather its web interface URL. You need to look the MJPEG URL up online to find it.

**Comment by xxllo** [comment]
Have an IP Cam from ESCAM qd300 and can not do to activate the cam in Monionpie it . What am I doing wrong???
