### ISSUE TITLE
Reset date

### ISSUE THREAD

**Issue by andrew81** [ccrisan/motionpie#294]
Date in motion pie has reset. Why?
Thanks

**Comment by ccrisan** [comment]
More details? Reset to what? 1970? Check the internet connectivity on your motionPie.

**Comment by andrew81** [comment]
Yes 1970. I see via internet... And sometimes camera disconnected about 5 second... May be it's problem camera

**Comment by ccrisan** [comment]
When your PI reboots (for whatever reason) it starts with 1970 as system date. It then uses the internet connection to retrieve the current date (HTTP on port 80). If that fails, your system time stays at 1970.

**Comment by drknstrmyknight** [comment]
There is no real-time clock or battery backed CMOS on a Raspberry, so when it is powered on the operating system has no way of determining the time or date. Motionpi will set the time and date from the internet if a connection is available.There are RTC hardware modules available if you have to run off-line.
