### ISSUE TITLE
Aircamdome url for motion pi

### ISSUE THREAD

**Issue by bjumy** [ccrisan/motionpie#296]
Hi

i have a raspberry pi 2 and i want to acces an ip camera in the same network 
The rasperry has motionpi and is connected to my network 192.168.30.171
Now the camera is on 30.199 but when i try to add the camera in the motionpi web interface
i can't get it done i need the right url only i do not know which url.

i found that the device url goes like this maybe i am using the wrong port?
rtsp://192.168.30.199:554/live/ch00_0

I need some help i have been at this for ages

thanks

**Comment by bjumy** [comment]
it says not a supported network camera but it is a ip network camera so i refuse to believe that

**Comment by ccrisan** [comment]
There is no support for RTSP (yet).
