### ISSUE TITLE
Schedule with capture still image

### ISSUE THREAD

**Issue by stephj915** [ccrisan/motionpie#300]
The schedule module seem working only with motion trigger. 
I would like using it when i capture still image.

eg : capture still image every 60 seconds  betwen 2pm and 7pm.

 Can you help me ?
Thank you.

**Comment by ccrisan** [comment]
That is not possible with the current implementation. There are no plans to extend the working schedule to other scenarios.

**Comment by stephj915** [comment]
ok thank you
