### ISSUE TITLE
login and password

### ISSUE THREAD

**Issue by gpgc67** [ccrisan/motionpie#303]
Hello, I have followed a procedure I found for installing MotionPie on to my Raspberry Pi 2. I installed the image onto an SD card, installed it in the Raspberry Pi 2, and powered it up. 
And before I get to the Motion Pie GUI, meaning I'm at a point where the screen is black and the letters are white, it's asking for a login and a password. I use admin as the login and with no password but I get a Login Incorrect error message. Does anyone know what this login and password should be?
I'm very new to Raspberry Pi and programming in general. I can't find a procedure that says what these should be. I think the admin login and no password belongs to the MotionPie window login, but I'm not there yet. 
I appreciate any help you can give me, thanks!

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motionpie/wiki/FAQ#i-am-only-getting-white-on-black-text-on-my-monitor-where-is-my-ui
