### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by ahollander** [ccrisan/motionpie#312]
When I check if the software is up to date, it confirms I have the most current, but it isn't. is this a software bug.

**Comment by ccrisan** [comment]
Please be more specific. What version do you run and what board do you use? What version do you expect?

**Comment by ahollander** [comment]
Calin,

First thank you for getting back so quickly. You've written great software and I've been using it for awhile now.

The issue with not updating the software happens with both the MotionPie 20150228 on Pi-B and on the Pi2 with 20150317.

Hope that clarifies.

Aaron


________________________________

**Comment by ccrisan** [comment]
The first *stable* version after 20150228 and 20150317 is [20150331](https://github.com/ccrisan/motionpie/releases/tag/20150331). If you read the notes, you'll see that there is an issue with the automatic updates and that you should download and reinstall the latest version manually.

**Comment by ahollander** [comment]
Thank you Calin!


________________________________
