### ISSUE TITLE
Failed writing header

### ISSUE THREAD

**Issue by vdyo** [ccrisan/motionpie#314]
Hi

I have just installed MotionPie on a Raspberry Pi2, installion went fine and I can log in.

The IP Camera I have is a Ubiquiti Networks Camera, the URL for the RTSP stream is rtsp://10.0.0.51:554/live/ch01_0 whne I enter this I get a Failed writing header error. If I put the Camera HTTP URL in, ie http://10.0.0.51 I get a camera not found.

Any idead?

Thanks

Damian

**Comment by ccrisan** [comment]
RTSP is not supported (yet) and the MJPG URL (if there is any) is probably something more complex than http://10.0.0.51; you need to look it up online or in your camera's manual.
