### ISSUE TITLE
cleanup

### ISSUE THREAD

**Issue by drknstrmyknight** [ccrisan/motionpie#317]
Could SAMBA be cleaned up a bit to keep these from junking up the logs?
Thanks! 

Jan  2 15:28:34 mp-f3800e00 daemon.err smbd[561]: [1970/01/02 15:28:34.128152,  0] ../source3/printing/print_standard.c:69(std_pcap_cache_reload)
Jan  2 15:28:34 mp-f3800e00 daemon.err smbd[561]:   Unable to open printcap file /etc/printcap for read!

**Comment by ccrisan** [comment]
Thanks for reporting the problem. I completely disabled printing support in `smb.conf`.
