### ISSUE TITLE
Add option to enable motion control listen on all interfaces.

### ISSUE THREAD

**Issue by Samfox2** [ccrisan/motionpie#330]
Hi, 

I have motioneye running and would like to request a snapshot from motion via its web interface from command line: 
curl -s -o /dev/null http://piip:8080/0/action/snapshot
or web browser:
http://piip:8080/0/action/snapshot

but it is not working.

Any idea why, does motioneye block any motion features?
http://www.lavrsen.dk/foswiki/bin/view/Motion/RemoteControlHttp for details on using http commands to control motion.

**Comment by ccrisan** [comment]
Motion control interface port is configured at 7999 and will only listen locally (i.e. on 127.0.0.1), for security reasons. If you want a snapshot, you can get it using the snapshot URL (see the Video Streaming section). For more details, see [this](https://github.com/ccrisan/motionpie/wiki/FAQ#whats-the-deal-with-snapshot-url-streaming-url-and-embed-url) wiki article.

**Comment by Samfox2** [comment]
Thanks for your answer. Unfortunately in my case no picture is created. May I ask you to test it with your configuration? Is it possible to disable the "local" listen feature for testing purposes?

**Comment by ccrisan** [comment]
I tested it and many users are using it. What URL do you use by the way?

P.S. I'll consider adding an option to enable motion HTTP control listening on all interfaces.

**Comment by Samfox2** [comment]
I tried it with:
curl -s -o /dev/null http://localhost:7999/0/action/snapshot but no pic was generated.

**Comment by ccrisan** [comment]
You seem to have ignored my answer. I'll try again: please use the Snapshot URL from the Video Streaming section of your motionPie. It should look something like http://ip:port/picture/1/current/?_username=admin&_signature=deadbeef

**Comment by Samfox2** [comment]
Hi ccrisan,

thanks for your help (again).
I was not ignoring your answer, I missunderstood it just a little bit.
However, I got it to work now :-)

What I wanted was to take an actual jpg-picture from my doorcam with an user defined event (a signal from my doorbell) while motioneye /-pie is running.

In my case this is:
curl -o "destination-filepath" myip:myport/picture/1/current

Afterwards I send it via telegram to my mobile phone.

Maybe this is also intresting for another motioneye /-pie user...
