### ISSUE TITLE
wpa_supplicant.log

### ISSUE THREAD

**Issue by drknstrmyknight** [ccrisan/motionpie#333]
using motionpie-raspberrypi-20150719

wpa_supplicant.log:

Successfully initialized wpa_supplicant
rfkill: Cannot open RFKILL control device
ioctl[SIOCSIWAP]: Operation not permitted

rfkill is not present in /dev

**Comment by ccrisan** [comment]
You can ignore those error messages. They won't affect your wifi setup. If your wifi doesn't work, it's because of other problems.

**Comment by drknstrmyknight** [comment]
Just one more thing to look at if troubleshooting wifi
