### ISSUE TITLE
Turn OFF webcam's led

### ISSUE THREAD

**Issue by surak** [ccrisan/motionpie#342]
Some webcams have a bunch of LEDs that point to the person looking at it. Those less can be enabled/disabled via software

It makes sense for videoconference, but not for surveillance. An option to turn off these leds is desirable.

**Comment by remonlam** [comment]
You mean the Pi camera?
That's kinda easy just add this line (disable_camera_led=1) to the /boot/config.txt

**Comment by iainbryden** [comment]
Error writing config.txt: Read-only file system

**Comment by ccrisan** [comment]
First of all, https://github.com/ccrisan/motionpie/blob/master/README.md.

Secondly, you should enable/disable the camera led from the settings panel, not by manually editing the config files. Mind you that the setting will only work for the Raspberry PI CSI camera.

And lastly, if you really want to manually edit the config.txt file: https://github.com/ccrisan/motionpie/wiki/Tweaks#partition-layout
