### ISSUE TITLE
attached camera can't be detected

### ISSUE THREAD

**Issue by selfcommander** [ccrisan/motionpie#358]
I see light on the camera. But MotionPie can't detect it. Attached is the screenshot of what I am seeing in web-interface, how it looks from outside and logs

http://s000.tinyupload.com/?file_id=54866614851102141702

**Comment by ccrisan** [comment]
Is this a clean install or did it happen after playing with some settings?

**Comment by selfcommander** [comment]
Clean

**Comment by selfcommander** [comment]
Also tried previous builds, with clean installs. Still can't find it

**Comment by ccrisan** [comment]
1) Your dmesg.log file says `[    4.524768] : bcm2835-v4l2: error -1 while loading driver`, which indicates a problem with your camera device. Check the ribbon cable connection, make sure you have at least 96 MB of RAM allocated to the GPU and if it still fails, try Raspbian and see if it works that way. If it doesn't, replace your camera board.

2) You should consider switching to [motionEyeOS](https://github.com/ccrisan/motioneyeos), as motionPie is discontinued and will not receive improvements and fixes anymore.

**Comment by selfcommander** [comment]
Camera was plugged into the wrong port -_-
The guy who owned it previously left it plugged in there, so I assumed it
is the right one...
Thanks for letting me know about new OS
