### ISSUE TITLE
can't connect to sshd

### ISSUE THREAD

**Issue by stenwt** [ccrisan/motionpie#371]
boot.log shows sshd started, but tcp 22 isn't listening. I can use the web ui to turn ftp, smb, sshd on or off, and it reflects in the boot.log. ftp and smb show up in a port scan when I activate them, ssh doesn't.

**Comment by ccrisan** [comment]
At first boot sshd creates its keys. If somehow the first boot sequence went wrong or didn't complete, those keys are absent. In that case I suggest rewriting the OS image from scratch.

**Comment by stenwt** [comment]
I was able to generate the keys manually and get in. Thanks!
