### ISSUE TITLE
Allowing two networks

### ISSUE THREAD

**Issue by rcjokibbe** [ccrisan/motionpie#372]
I'm not sure this is an issue, but I don't know where else to ask.  How can I connect an ip camera to the raspberry using the ethernet port and use the raspberry's wireless card to connect to the home network?  The home's wireless router isn't reliable and I need to have motioneyeos continue capturing video from the ip camera.  I'm confused what to edit so I get both eth0 and wlan0 working at the same time.

**Comment by ccrisan** [comment]
You can't with motionPie nor with motionEyeOS. The OS is designed to connect only to one network. If you really need it connected to both networks, please use Raspbian + motionEye.
