### ISSUE TITLE
username and password to log into the Raspi

### ISSUE THREAD

**Issue by gerryhome** [ccrisan/motionpie#373]
Hi, great job. But I have a question.
I wanted my noip package to install on the Raspberry.
But I'm not with putty in the raspberry. How then is the username and password?

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#command-line--shell-access and https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-cant-seem-to-find-apt-get-or-any-other-package-manager-what-gives
