### ISSUE TITLE
What is the difference between motionPie and motionEyeOS

### ISSUE THREAD

**Issue by chfakht** [ccrisan/motionpie#374]
Hi , please can you tell the differences between motionPie and motionEyeOS ,
i'm looking for other reasons other than these reasons 
The reasons for renaming the project include:

1. Reventing the missassociation with the Raspberry PI (motionEyeOS now supports 5 different boards)
2. avoiding name confusions generated by all the projects built around motion
3. pointing out that this is an operating system based on and built especially for motionEye
4. the name motionPie simply sucks

what i want to do is to install motionPie alongside with raspbian so i don't want to put all the img on the SD Card ... Can this be possible

**Comment by ccrisan** [comment]
There are no other reasons. You can't install motionPie alongside with Raspbian. You are probably looking for [motionEye](https://github.com/ccrisan/motioneye) which is just the frontend, w/o the underlying OS.

**Comment by chfakht** [comment]
ok thanks
