### ISSUE TITLE
File storage, update service file location

### ISSUE THREAD

**Issue by landru500000** [ccrisan/motionpie#375]
at 23:56 on 1/29 I changed the file location on google drive to a new file directory on google drive.

on 1/30, i checked the google drive.  it contained some pictures that motioneyeos had updated which i expected.   I then logged to motioneyeos, and i noticed that file location was still what appeared the prior day.  ( as shown in the location field in upload service section)

Is it possible that the file location internally is being changed (because the pictures are being uploaded to google drive by motioneyeos) but the user interface does not show the proper file target directory on google drive?

**Comment by ccrisan** [comment]
Behind the scenes, the path on google drive is in fact referred by a folder id. If you simply moved around the folder or renamed it on your Google Drive UI, its id probably had remained the same and therefore, inspite its old name showing up in motionEye UI, the files would have been placed correctly at the new location.
