### ISSUE TITLE
Security: Page in Embed URL contains admin password

### ISSUE THREAD

**Issue by acuntex** [ccrisan/motionpie#379]
The Basic Authentication seems useless because the Embed Site contains the following code:

        <div class="camera-frame" id="camera1"
                streaming_framerate="" streaming_server_resize=""
                proto="mjpeg" url="http://user:password@127.0.0.1:8081/">

There is an authentication dialog but the video is in the background and you can just cancel the dialog to get the video.

This also means that the password is saved plaintext.

Would it be possible to remove any password from the web interface?
Would it be possible to hash the password?

Thanks!

**Comment by ccrisan** [comment]
I'm not sure why you have closed this issue. Nevertheless I think the decision behind this deserves an explanation:

This case is valid only when using Simple MJPEG Cameras, which is most likely used when enabling Fast Network Camera. In this mode, motionEye should be seen as a configuration UI for the camera and not a DVR frontend. Therefore, the MJPEG stream played directly by the browser should only be seen while configuring the camera.
