### ISSUE TITLE
Expert Panel is missing in 0.31.3

### ISSUE THREAD

**Issue by bfmorgan** [ccrisan/motionpie#383]
With Advanced Settings 'On', I cannot see the Expert panel on raspbien jesse and using the installation notes on installing MotionEye. When I installed the motioneyeos image I saw the expert panel, but when installing onto raspbien, there is not expert panel. Everything else works.

Sorry if this is another loose nut at the keyboard.

**Comment by ccrisan** [comment]
Can I see a screenshot?

**Comment by ccrisan** [comment]
Ah, nevermind, there is no Expert Settings in plain motionEye.

**Comment by bfmorgan** [comment]
Is there away other than install the image for motioneysOS?

**Comment by bfmorgan** [comment]
Thanks by the way for responding so quickly. Love your work.
