### ISSUE TITLE
VCGENCMD - How do I add this to the motionpie image.  I want to check CPU Temperature

### ISSUE THREAD

**Issue by dkwizard1** [ccrisan/motionpie#384]
I would like to add the VCGENCMD to the Motionpie image so I can SSH into it and read the CPU temperature.  I found the following command that will do this with a Raspberry Pi Image, but when I try this on the motionpie image it says command not found.  I also notice that the sudo apt-get update command doesn't run either.  I doesn't like sudo or the apt-get commands.

/opt/vc/bin/vcgencmd measure_temp
If you want to watch it continuously, use:

1
watch /opt/vc/bin/vcgencmd measure_temp

**Comment by ccrisan** [comment]
vcgencmd is already part of the OS. Just run it directly from /usr/bin, not from /opt. Also, please switch to [motionEyeOS](https://github.com/ccrisan/motioneyeos)
