### ISSUE TITLE
Storage settings on 64GB microSD card

### ISSUE THREAD

**Issue by tobriain** [ccrisan/motionpie#390]
I've written the MotionPie image to a 64GB card, but can't seem to resize any of the partitions to make use of the extra storage for pictures and videos. 

I started with a 64GB card with a single FAT32 partition and wrote the image to the card. Now I have a 16MB FAT16 partition, a 120MB 'Other' parition and 58GB unallocated. Using a standard partition manager, I can't expand any of the partitions. 

Any tips on how to do this appreciated!

**Comment by ccrisan** [comment]
Use motionEyeOS (motionPie has been discontinued). At first boot the OS will automatically create a partition from all the unallocated space.
