### ISSUE TITLE
Save videos in sd, then on a linux server

### ISSUE THREAD

**Issue by mike94pi** [ccrisan/motionpie#402]
Hello, 
First of all, thank you for your awesome job.
I want to save the movies first on the sd card, for example save 5gb of movies and then transfer them to a server. Is this possible?

**Comment by ccrisan** [comment]
Yes. Please switch to [motionEyeOS](https://github.com/ccrisan/motioneyeos) if you haven't done it already. Then use FTP, SFTP or SMB (windows network) to access the files on your SD card and transfer them wherever you want.
