### ISSUE TITLE
Default to AP mode when no wifi network available

### ISSUE THREAD

**Issue by sticilface** [ccrisan/motionPie#65]
I've been trying to get this to reliably work with rasbian, and had some success although not a great deal.  

Would be great for motionpie as the device may itself be trapped in an enclosure and not easy to access.  Currently it reboots if no network is found, but say after 5 times is could default to AP mode, maybe periodically turning it off to rescan for available APs.  At least then you could get to it to change settings...  

for example your wifi config has changed...  

This is great though... took 2 min to flash an SD card and i have a remote camera working out the box.  Keep up the good work!

**Comment by ccrisan** [comment]
Unfortunately this is not going to be possible, at least not with the current wifi drivers - they rarely can be put in AP mode.
