### ISSUE TITLE
backup sdcard while its working in the Pi

### ISSUE THREAD

**Issue by dkelley810** [ccrisan/motionPie#67]
I was wondering if there is a way to backup my SD card while it is in the working Raspberry Pi?
Or do i have to remove it and back it up in another computer?

Thank You for the Great work and Support!

**Comment by ccrisan** [comment]
Your only option is to put the card into a PC running Linux (or maybe OSX?) and copy the contents of the data partition (the third one). Those are all the media and config files of your motionPie.

**Comment by dkelley810** [comment]
Thanks Again!
