### ISSUE TITLE
WARNING: mjpg client connection for camera 1 on port 8081 is closed

### ISSUE THREAD

**Issue by piecam** [ccrisan/motionPie#79]
HI,
Why does my main gui motioneye go to blackness from time to time? Is it I set resolution too high?

I have one b+ with normal Pi cam and one b+ with Pi NoIR cam. it looks that the normal one's gui is ok. the NoIR's one gets this issue. Both are 1600x1200.

If I reduce NoIR's resultion a bit like 1440x960 or even lower, it looks it stays there for a whiel.
CPu is about 97%-100% with gui open.
tks
peng

**Comment by ccrisan** [comment]
Resolutions over 1280x720 (I think) use "stills mode" which needs some time to capture the image, otherwise it becomes darker and darker. Use lower resolutions.
