### ISSUE TITLE
ability to save settings from Web Interface

### ISSUE THREAD

**Issue by dkelley810** [ccrisan/motionPie#86]
I think a good feature would be the ability to save the setting of the Web Interface. I finally have all my settings working great. Everything is set exactly how I want. I want to be able save the setting in case an update messes something up. or is there a file I can copy from somewhere?

**Comment by ccrisan** [comment]
This is not a bad idea at all. Until I'll find some spare time to implement it, you can simply save/restore /data/etc directory.

**Comment by ccrisan** [comment]
It's been around since 20150315.
