### ISSUE TITLE
Cisco Linksys WVC-200

### ISSUE THREAD

**Issue by piecam** [ccrisan/motionPie#91]
HI,
I have two linksys wvc-200 from a few years back, when it was about $250/pc. I tried on MP, and it doesn't get connected with user/pass.
I tried this link, http://www.lavrsen.dk/foswiki/bin/view/Motion/LinksysWVC200SupportPatch

netcam_url mjpg://netcam-ip:port/img/video.mjpeg 

My adapted version is http://admin:admin@x.x.x.x:80/img/video.mjped.

Any advice?
tks

**Comment by ccrisan** [comment]
What http authentication method does it use? Only basic authentication is supported by the motion daemon.

**Comment by piecam** [comment]
#EXTM3U
http://admin:zzzzz@192.168.1.21/img/video.asf

This is what I used for VLC to play. However, With firefox, just standard HttP.

thanks

**Comment by ccrisan** [comment]
Most likely your camera requires HTTP digest authentication, which is not supported by motion.
