### ISSUE TITLE
frame rate,streaming frame rate,snapshort url,streaming url,embed url

### ISSUE THREAD

**Issue by piecam** [ccrisan/motionPie#92]
HI,
Can we have a clear definition and difference of all these setting?
Is "frame rate" the fundamental one that will affect anything else? Does cam constatly capture image with this rate in RAM and discard it if not processed?

Is streaming frame rate determined by "frame rate"? Higher "streaming frame rate" doesn't achieve much if you have a less "frame rate"? 

What's the difference between these URL? Are they getting same "streaming" from port 8081? Are they essentially the same source and refreshed by "streaming frame rate"? 
thanks

**Comment by ccrisan** [comment]
For the two framerates, see [framerate](http://www.lavrsen.dk/foswiki/bin/view/Motion/ConfigOptionFramerate) and [webcam_maxrate](http://www.lavrsen.dk/foswiki/bin/view/Motion/ConfigOptionWebcamMaxrate).

For the URLs, use the tooltip under the "?" question mark next to each option. I couldn't make them any clearer.
