### ISSUE TITLE
Minimizable config sections

### ISSUE THREAD

**Issue by dkelley810** [ccrisan/motionPie#93]
I sometimes make adjustments to General Settings from my cell phone. It would be nice to close some settings without actually turning them off. Like for instance if I click on Wireless Network does it turn off wireless? I want to just turn off the settings not turn off wireless. so maybe a button to on/off/'minimize'

**Comment by ccrisan** [comment]
I don't think the benefits of having this feature are worth the amount of work that needs to be done for it.

**Comment by ccrisan** [comment]
I decided to implement your idea after all. The settings panel looks clearer now, indeed. @dkelley810, thanks for your idea.
