### ISSUE TITLE
Cron?

### ISSUE THREAD

**Issue by badger28** [ccrisan/motionPie#96]
Cron doesn't seem to be present...
Is there anyway I can use cron within motionpie to update a dynamic ip address?

This would allow me to view the stream while I am away from home.  Or is there an easier way of me achieving this?

Thanks

**Comment by ccrisan** [comment]
No, there's no such option, for now.

**Comment by ccrisan** [comment]
Duplicate of https://github.com/ccrisan/motionPie/issues/127
