### ISSUE TITLE
feature request - schedule reboots

### ISSUE THREAD

**Issue by snagglewest** [ccrisan/motionPie#98]
I'd like to request a new feature to reboot on a predetermined schedule.  

I'm using MotionPie with zoneminder and occasionally I'm getting disconnects on zoneminder, maybe once ever week or so but there's no firm pattern that I can find.  I'm not sure exactly what's causing it as MotionPie is still accessible from the web interface, but a reboot fixes the connection.  A function much like the "work schedule" to set a reboot for every day, week, etc. would be helpful if it's not too much trouble to implement.

**Comment by ccrisan** [comment]
I don't think this is useful enough to make it worth the trouble of implementing it.
