### ISSUE TITLE
Use brightPi?

### ISSUE THREAD

**Issue by Roelofloots** [ccrisan/motionPie#99]
Just want to know, if i buy a BrightPi, will it work on motionPi? I want to ad some light to my pi noir and brightpi seems to be the easy solution, but looks like it needs scripts to activate the lights, which im not sure if it will be possible with this?

**Comment by ccrisan** [comment]
There is no support for this accessory in motionPie, for now/

**Comment by lastfreenick** [comment]
I got this http://m.ebay.de/itm/291309642414?txnId=1111478531019 and this http://m.ebay.de/itm/181471891593?txnId=1294112615008 for my noir cam. Great value for 5€ I guess similar solutions are available for regular (non ir) lighting, if you just want always on light in the night.
